//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Book_Id { get; set; }
        public int Genre_Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int Year { get; set; }
        public decimal Price { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Genres Genres { get; set; }
    }
}
